"""Application-facing facades for JobDesk's supported use cases."""

from .confflow_client import (
    ArtifactEntry,
    ArtifactManifest,
    ConfFlowClient,
    ConfFlowClientError,
    EventPage,
    RemoteRunHandle,
    RemoteRunReference,
    RemoteRunSnapshot,
    SubmitRequest,
    TaskSnapshot,
    UnsupportedRemoteRunOperation,
)
from .container import ApplicationContainer
from .facades import (
    DownloadResult,
    FilesApplication,
    RecoveryResult,
    RemoteFileEntry,
    RunApplication,
    RunDetails,
    RunEvent,
    RunQuery,
    RunSubscription,
    RunSummary,
    ScalarOption,
    ServerSnapshot,
    SettingsApplication,
    SettingsSnapshot,
    SubmitRunRequest,
    SubmitRunResult,
    TaskSummary,
    TransferResult,
    WorkflowApplication,
    WorkflowPreset,
    WorkflowValidation,
)
from .file_transfer_ports import FileTransferPort, RemoteEntryLike, TransferRecordLike
from .files_browser import (
    FileBrowserEntrySnapshot,
    FileBrowserSnapshot,
    FilesBrowserController,
)
from .files_connections import FilesConnectionController, FileTransferConnectionSnapshot
from .gui_ports import (
    ConnectionSnapshot,
    FilesPagePort,
    FileTargetSnapshot,
    PageRefreshPort,
)
from .outcomes import ApplicationClosedError, OperationFailure, OperationOutcome
from .run_tasks import RunTaskLookup
from .runs_monitor import (
    MonitorContext,
    MonitorEvent,
    MonitorPort,
    MonitorSubscription,
    RunMonitorController,
    RunsMonitorController,
    monitor_watch_id,
)
from .runs_query import (
    RunQueryController,
    RunQueryResult,
    RunQuerySnapshot,
    RunSelectionSnapshot,
    RunSelectionState,
)
from .runs_runtime import (
    MonitorRunInput,
    RunsMonitorInput,
    RunsPageRuntime,
)

__all__ = [
    "ApplicationClosedError",
    "ApplicationContainer",
    "ArtifactEntry",
    "ArtifactManifest",
    "ConfFlowClient",
    "ConfFlowClientError",
    "EventPage",
    "RemoteRunHandle",
    "RemoteRunReference",
    "RemoteRunSnapshot",
    "SubmitRequest",
    "TaskSnapshot",
    "UnsupportedRemoteRunOperation",
    "ConnectionSnapshot",
    "FileTargetSnapshot",
    "FilesPagePort",
    "PageRefreshPort",
    "MonitorContext",
    "MonitorEvent",
    "MonitorPort",
    "MonitorSubscription",
    "RunMonitorController",
    "RunsMonitorController",
    "monitor_watch_id",
    "RunsPageRuntime",
    "MonitorRunInput",
    "RunsMonitorInput",
    "FileBrowserEntrySnapshot",
    "FileBrowserSnapshot",
    "FilesBrowserController",
    "FileTransferPort",
    "RemoteEntryLike",
    "TransferRecordLike",
    "FileTransferConnectionSnapshot",
    "FilesConnectionController",
    "RunQueryController",
    "RunQueryResult",
    "RunQuerySnapshot",
    "RunSelectionSnapshot",
    "RunSelectionState",
    "RunTaskLookup",
    "DownloadResult",
    "FilesApplication",
    "OperationFailure",
    "OperationOutcome",
    "RecoveryResult",
    "RemoteFileEntry",
    "RunApplication",
    "RunDetails",
    "RunEvent",
    "RunQuery",
    "RunSubscription",
    "RunSummary",
    "ScalarOption",
    "ServerSnapshot",
    "SettingsApplication",
    "SettingsSnapshot",
    "SubmitRunRequest",
    "SubmitRunResult",
    "TaskSummary",
    "TransferResult",
    "WorkflowApplication",
    "WorkflowPreset",
    "WorkflowValidation",
]
