#!/usr/bin/env python3

"""Shared, dependency-light helpers used across package boundaries."""

from __future__ import annotations

from .defaults import (
    BOLTZMANN_ENERGY_CUTOFF,
    DEFAULT_CHARGE,
    DEFAULT_CORES_PER_TASK,
    DEFAULT_ENABLE_DYNAMIC_RESOURCES,
    DEFAULT_FORCE_CONSISTENCY,
    DEFAULT_MAX_PARALLEL_JOBS,
    DEFAULT_MULTIPLICITY,
    DEFAULT_RESUME_FROM_BACKUPS,
    DEFAULT_RMSD_THRESHOLD,
    DEFAULT_SCAN_COARSE_STEP,
    DEFAULT_SCAN_FINE_STEP,
    DEFAULT_SCAN_UPHILL_LIMIT,
    DEFAULT_STOP_CHECK_INTERVAL_SECONDS,
    DEFAULT_TOTAL_MEMORY,
    DEFAULT_TS_BOND_DRIFT_THRESHOLD,
    DEFAULT_TS_RESCUE_SCAN,
    DEFAULT_TS_RMSD_THRESHOLD,
)
from .orca_blocks import format_orca_blocks

__all__ = [
    "DEFAULT_CORES_PER_TASK",
    "DEFAULT_TOTAL_MEMORY",
    "DEFAULT_MAX_PARALLEL_JOBS",
    "DEFAULT_CHARGE",
    "DEFAULT_MULTIPLICITY",
    "DEFAULT_RMSD_THRESHOLD",
    "DEFAULT_TS_RESCUE_SCAN",
    "DEFAULT_SCAN_COARSE_STEP",
    "DEFAULT_SCAN_FINE_STEP",
    "DEFAULT_SCAN_UPHILL_LIMIT",
    "DEFAULT_TS_BOND_DRIFT_THRESHOLD",
    "DEFAULT_TS_RMSD_THRESHOLD",
    "DEFAULT_ENABLE_DYNAMIC_RESOURCES",
    "DEFAULT_RESUME_FROM_BACKUPS",
    "DEFAULT_STOP_CHECK_INTERVAL_SECONDS",
    "DEFAULT_FORCE_CONSISTENCY",
    "BOLTZMANN_ENERGY_CUTOFF",
    "format_orca_blocks",
]
