#!/usr/bin/env python3

"""ConfFlow centralized default value definitions.

All modules should reference defaults from this file to avoid hard-coding.
"""

from __future__ import annotations

__all__ = [
    "DEFAULT_CORES_PER_TASK",
    "DEFAULT_TOTAL_MEMORY",
    "DEFAULT_MAX_PARALLEL_JOBS",
    "DEFAULT_CHARGE",
    "DEFAULT_MULTIPLICITY",
    "DEFAULT_RMSD_THRESHOLD",
    "DEFAULT_TS_RESCUE_SCAN",
    "DEFAULT_SCAN_COARSE_STEP",
    "DEFAULT_SCAN_FINE_STEP",
    "DEFAULT_SCAN_UPHILL_LIMIT",
    "DEFAULT_TS_BOND_DRIFT_THRESHOLD",
    "DEFAULT_TS_RMSD_THRESHOLD",
    "DEFAULT_ENABLE_DYNAMIC_RESOURCES",
    "DEFAULT_RESUME_FROM_BACKUPS",
    "DEFAULT_STOP_CHECK_INTERVAL_SECONDS",
    "DEFAULT_FORCE_CONSISTENCY",
    "BOLTZMANN_ENERGY_CUTOFF",
]

# Resource defaults
DEFAULT_CORES_PER_TASK = 1
DEFAULT_TOTAL_MEMORY = "4GB"
DEFAULT_MAX_PARALLEL_JOBS = 1

# Chemistry defaults
DEFAULT_CHARGE = 0
DEFAULT_MULTIPLICITY = 1

# Refine defaults
DEFAULT_RMSD_THRESHOLD = 0.25

# TS (transition state) defaults
DEFAULT_TS_RESCUE_SCAN = False
DEFAULT_SCAN_COARSE_STEP = 0.1
DEFAULT_SCAN_FINE_STEP = 0.02
DEFAULT_SCAN_UPHILL_LIMIT = 10
DEFAULT_TS_BOND_DRIFT_THRESHOLD = 0.4
DEFAULT_TS_RMSD_THRESHOLD = 1.0

# Workflow defaults
DEFAULT_ENABLE_DYNAMIC_RESOURCES = False
DEFAULT_RESUME_FROM_BACKUPS = True
DEFAULT_STOP_CHECK_INTERVAL_SECONDS = 1
DEFAULT_FORCE_CONSISTENCY = False

# Boltzmann weight cutoff (kcal/mol)
BOLTZMANN_ENERGY_CUTOFF = 50.0
